version: '3.4'

services:
  todoangulargraphql.server:
    environment:
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS = true
  todoangulargraphql.client:
    volumes:
      - ./ToDoAngularGraphQL.Client:/app
      - "node_modules:/app/node_modules"
volumes:
  node_modules: